Repository EsotericSoftware/kryo, pull requests merged in 2021-07, with the labels that each got.

#839 avoid flush repeatedly when has finished flushing
  src/com/esotericsoftware/kryo/io/OutputChunked.java
Labels: enhancement

#841 #840 Ensure primitive types are assignable to Comparable/Serializable fields
  src/com/esotericsoftware/kryo/util/Util.java
  test/com/esotericsoftware/kryo/serializers/CompatibleFieldSerializerTest.java
  test/com/esotericsoftware/kryo/util/UtilTest.java
Labels: bug

#848 #847 Ensure that `RecordSerializer` can deal with subtypes
  src/com/esotericsoftware/kryo/serializers/RecordSerializer.java
  test-jdk14/com/esotericsoftware/kryo/TestDataJava14.java
  test-jdk14/com/esotericsoftware/kryo/serializers/RecordSerializerTest.java
Labels: breaks compatibility, bug
